[package]
name = "ocaml-rust-arrow"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
ocaml-rust = "0.0.1"
ocaml-sys = "0.22.3"
arrow = "12.0.0"
parquet = "12.0.0"
